### ISSUE TITLE
Which library to use?

### ISSUE THREAD

**Issue by ajostergaard** [PinchProject/Node-GCMService#2]
Hi,

I noticed that this library was based on node-gcm by ToothlessGear. This one seems a little better mostly due to providing convenient access to the response details. However I noticed that around the same time as you last edited this library you were also contributing to node-gcm. Also node-gcm seems popular but has error handling bugs which have been outstanding for a long time. So ... ? :-S

AJ

**Comment by ghost** [comment]
Hi,

All I can say is that you must try all GCM modules to determine which meets your needs. I create this module based on node-gcm api and I have added everything we needed for our server (at PinchProject).

**Comment by ajostergaard** [comment]
Ok. Thanks.
